services:
  traefik:
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"

  backend:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  frontend:
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"

  postgres:
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  redis:
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"

  mailhog:
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"

  adminer:
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"

