version: "3.9"

services:
  frontend:
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro

  backend:
    environment:
      - APP_ENV=development
    volumes:
      - ./src/backend:/app:ro

