version: "3.9"

services:
  backend:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  frontend:
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    deploy:
      restart_policy:
        condition: on-failure

  mailhog:
    deploy:
      restart_policy:
        condition: on-failure

