http:
  middlewares:
    api-rate-limit:
      rateLimit:
        average: 100
        burst: 50

    secure-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true

    backend-cors:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Origin"
          - "Content-Type"
          - "Accept"
        accessControlAllowOriginList:
          - "https://app.localhost"
          - "http://app.localhost"
        accessControlMaxAge: 100
        addVaryHeader: true

    gzip-compression:
      compress: {}

